// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqldb

import (
	"time"
)

type AuthToken struct {
	Token       string
	ParentToken string
	CreatedAt   time.Time
}

type Event struct {
	UUID        string
	CreatedAt   time.Time
	Description string
}

type EventAttendee struct {
	EventUUID string
	UserCode  string
	CreatedAt time.Time
}

type User struct {
	Email string
	Code  string
	Name  string
}
