// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqldb

import (
	"time"
)

type Event struct {
	UUID        string
	CreatedAt   time.Time
	Description string
}

type EventAttendee struct {
	EventUUID string
	UserUUID  string
	CreatedAt time.Time
}

type User struct {
	UUID  string
	Name  string
	Email string
}
